/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
 @QQ Group : 627141737

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Default Save": "默认存档",
    "Delete": "删除",
    "No": "否",
    "Saves": "存档",
    "Options": "选项",
    "Yes": "是",
    "Are you sure?": "你确定吗？",
    "Edit Name": "编辑名称",
    "Info": "信息",
    "Currently:": "当前:",
    "Appearance": "外观",
    "How the game looks.": "游戏看起来如何。",
    "Theme": "主题",
    "Show milestones": "显示里程碑",
    "Show TPS meter at the bottom-left corner of the page.": "在页面左下角显示 TPS。",
    "Show TPS": "显示 TPS",
    "None": "无",
    "Align modifier units": "对齐概览单位",
    "Align numbers to the beginning of the unit in modifier view.": "在概览视图中将数字与单元的开头对齐。",
    "Select which milestones to display based on criterias.": "根据标准选择要显示的里程碑。",
    "All": "全部",
    "Classic": "经典",
    "Configurable": "可配置",
    "Duplicate": "复制",
    "Mute": "静音",
    "Unmute": "播放",
    "Join the Discord!": "加入 Discord!",
    "Upgrades": "升级",
    "Toy Thief": "玩具小偷",
    "Toy Machine": "玩具机器",
    "Thanks for playing!": "感谢你玩本游戏！",
    "This is your Toy Machine, click on it and try to make 10 toys.": "这是你的玩具机器，点击它并尝试制作10个玩具。",
    "-Music": "-音乐",
    "Active Upgrades": "可用升级",
    "Elf": "精灵",
    "Dreams": "梦",
    "Conveyor": "传送带",
    "Clicks": "点击",
    "Clicks lost in dreams": "点击迷失在梦境中",
    "animations:": "动画:",
    "Items": "物品",
    "import": "导入",
    "reset": "重置",
    "Robot": "机器人",
    "Santasperience": "圣诞圣诞经验值",
    "save": "保存",
    "Planet": "星球",
    "stats": "统计",
    "Vortex": "涡漩",
    "Golden gift clicks": "金色礼物点击",
    "Gifts in storage": "仓库中的礼物",
    "press ctrl+shift+r to refresh if the page does not load!": "如果页面没有加载，按ctrl+shift+r刷新！",
    "On a very cold winter evening...": "在一个非常寒冷的冬夜…",
    "menu": "菜单",
    "Giftwrapper": "礼物包装器",
    "Gifts per click": "每次点击的礼物",
    "export": "导出",
    "Factory": "工厂",
    "Gifts made": "制作的礼物",
    "achievements": "成就",
    "Active Santasperience": "活跃的圣诞圣诞经验值",
    "Duplicator": "复制器",
    "Forklift": "叉车",
    "Gifts lost in dreams": "梦中丢失的礼物",
    "Gifts made by clicks": "点击制作的礼物",
    "Gifts made this dream": "礼物成就了这个梦",
    "At least one decent spam advertisement": "至少有一个像样的垃圾广告",
    "add 0.1 toys for each item you have when clicking": "点击时，每拥有一个物品，增加0.1个玩具",
    "Childhood all over again": "重温童年",
    "Coffee": "咖啡",
    "Helps the brain to wake up": "帮助大脑清醒",
    "Hmmm i've done this before": "嗯，我以前做过这种事",
    "Memory Pills": "记忆药丸",
    "Hypnotherapy": "催眠疗法",
    "My first french kiss": "我的第一个法式热吻",
    "Read the manual": "阅读说明书",
    "So much work": "这么多工作",
    "Santa’s most loyal helper": "圣诞老人最忠实的帮手",
    "Sweating my xmas balls off": "出汗把我的圣诞球弄掉了",
    "game saved": "游戏已保存",
    "A long way from home": "离家很远",
    "Deja vu": "似曾相识的感觉",
    "Deliver to Africa": "交付到非洲",
    "Deliver to Europe": "交付到欧洲",
    "Deliver to Asia": "交付到亚洲",
    "Deliver to North America": "交货至北美",
    "Deliver to Oceania": "交货至大洋洲",
    "Deliver to South America": "交货至南美",
    "double conveyor production": "传送带生产翻倍",
    "double elf production": "精灵产量翻倍",
    "Here they make snow from plants": "在这里，他们用植物造雪",
    "I hope my reindeer don't get shot": "我希望我的驯鹿不会中枪",
    "Improved cogwheels": "改良齿轮",
    "Magic? Or are there elves in the machine?": "魔法？还是机器里有精灵？",
    "Minifitness": "小型化",
    "Must be boring to be a conveyor": "当传送带一定很无聊吧",
    "Nothing they can't handle": "没有他们处理不了的",
    "These titanium cogwheels won't break": "这些钛制齿轮不会坏",
    "Who the hell reads this anyway": "到底谁会读这篇文章",
    "\tContact us on reddit or email": "\t请通过Reddit或电子邮件联系我们",
    "\tHave something to say? Good or Bad it doesn't matter!": "\t有什么要说的吗？是好是坏都无所谓！",
    "\tReddit username: FloriLou": "\tReddit 用户名: FloriLou",
    "God of Gifts": "礼物之神",
    "Deliver gifts to Africa": "交付礼物到非洲",
    "Deliver gifts to Europe": "交付礼物到欧洲",
    "Deliver gifts to world": "交付礼物到世界",
    "Deliver gifts to Asia": "交付礼物到亚洲",
    "Deliver gifts to North America": "交付礼物到北美",
    "Deliver gifts to Oceania": "交付礼物到大洋洲",
    "Deliver gifts to South America": "交付礼物到南美",
    "Deliver gifts to South Amerika": "把礼物送到南美",
    "Dirty Mind": "肮脏的思想",
    "Asia": "亚洲",
    "Africa": "非洲",
    "Europe": "欧洲",
    "Oceania": "大洋洲",
    "North America": "北美",
    "South America": "南美",
    "World": "世界",
    "Mouse Phobia": "鼠标恐惧症",
    "Winner": "赢家",
    "A Clear Mind": "头脑清醒",
    "AchieveCeption": "成就异常",
    "Apprentice Achiever": "学徒成功者",
    "Beginner's Luck": "新手的好运气",
    "Bringer of Gifts": "礼物使者",
    "DecaBuilding": "十层建筑",
    "Deliver all gifts to earth in less than a minute": "在一分钟内把所有的礼物送到地球",
    "Double HectoBuilding": "双百建设",
    "Gift Billionaire": "礼物亿万富翁",
    "Gifted": "天赋异禀",
    "Have exactly 1 item of each": "每种物品都有一件",
    "Have exactly 69 items of each": "每种物品都有69个",
    "HectoBuilding": "赫克托大厦",
    "Jackpot": "大奖",
    "Laboratoy": "实验室",
    "Lazy": "懒惰",
    "Like SantaCeption": "点赞圣诞礼物放置",
    "Lonely": "孤独",
    "Lucky or Unlucky?": "幸运还是不幸？",
    "Lucky Spinner": "幸运转轮",
    "Lucky times Unlucky": "时运不济",
    "Minute Man": "分钟人",
    "Moving on to the Next World": "进入下一个世界",
    "My first gifts": "我的第一份礼物",
    "My House is Getting too Small": "我的房子太小了",
    "North Pole Overcrowded": "北极人满为患",
    "Oceania": "大洋洲",
    "Overachiever": "高成就者",
    "Perfectionist": "完美主义者",
    "Progress": "进度",
    "Santa likes you too!": "圣诞老人也喜欢你！",
    "Scientist": "科学家",
    "Spacelab": "太空实验室",
    "The Galaxy is Mine": "银河系是我的",
    "This one is mine": "这一个是我的",
    "Toy Machine God": "玩具机器神",
    "Winner Winner, Chicken Dinner": "大吉大利，今晚吃鸡",
    "Work Work": "工作工作",
    "You always deliver this fast?": "你们交货总是这么快？",
    "Your loves makes everything 10% more powerful": "你的爱让一切都变得强大10%",
    "What’s up with the gold ones?": "那些金色的是怎么回事？",
    "Gone with those old-fashioned gifts": "那些老式的礼物都不见了",
    "Electronic Toys": "电子玩具",
    "double toymachine production": "玩具机器生产翻倍",
    "Deliver gifts to the world": "给全世界送礼物",
    "+1% of your total production each klik": "每公里+1%的总产量",
    "Brush and Dustpan": "刷子和簸箕",
    "Clean the gifts fallen from the machines": "清理从机器上掉下来的礼物",
    "Gets everything done faster": "让一切都做得更快",
    "Manager Elf": "经理精灵",
    "It's all legal in santa land": "这在圣诞老人的世界里是合法的",
    "Steroids": "类固醇",
    "best rubber on the planet": "世界上最好的橡胶",
    "Dissolve Labor Union": "解散工会",
    "double robot production": "机器人生产翻倍",
    "Hard Rubber": "硬橡胶",
    "Improved Robotics": "改良机器人",
    "Oh, What´s this? A golden gift?": "哦，这是什么？金色的礼物？",
    "These elves have no rights anymore": "这些精灵再也没有权利了",
    "Try to catch it!": "试着抓住它！",
    "Will this make a new kind of robot?": "这会产生一种新的机器人吗？",
    "double giftwrapper production": "双倍金色包装纸生产",
    "Giftwrapper drops 1 golden gift more each time": "金色包装纸每次多掉落1个金色礼物",
    "Goldwrapper": "金色包装纸",
    "Just paste it on the gift": "把它贴在礼物上",
    "Never run out of toy recources": "永远不会耗尽玩具资源",
    "Newest sort of paper, santaception patent pending": "最新的纸张，专利申请中",
    "Premade Gift Bows": "预制礼品蝴蝶结",
    "Resource contract": "资源合同",
    "add 1 toys for each item you have when clicking": "点击时，每拥有一件物品增加1个玩具",
    "Better work atmosphere": "更好的工作氛围",
    "Motivational posters": "励志海报",
    "Sugar Rush": "糖潮",
    "Way to much candy yesterday": "昨天吃太多糖了",
    "Does it even lift?": "它能举起来吗？",
    "Automated Guided Vehicle": "动导引车",
    "AI": "AI",
    "Better grip": "更好的抓握",
    "Burglar Tools": "防盗工具",
    "Community service in Santaland": "圣诞乐园的社区服务",
    "double toy thieves production": "玩具小偷生产翻倍",
    "double vortex production": "涡漩生产翻倍",
    "double thieves production": "小偷生产翻倍",
    "double forklift production": "叉车生产翻倍",
    "double duplicator production": "复制器生产翻倍",
    "Duplicates all but Santa himself": "除了圣诞老人，其他都复制了",
    "Elf Army": "精灵军团",
    "Google helped us": "谷歌帮助了我们",
    "Learn from your mistakes": "从错误中吸取教训",
    "Nothing will slip": "没有东西会滑落",
    "Sir, Yes Sir!": "长官，是的长官！",
    "Now they can enter anywhere": "现在他们可以进入任何地方",
    "No faulty wrapped gifts anymore": "没有错误包装的礼物了",
    "Improved mechanics": "改善机制",
    "Weirdly it's only twice as fast": "奇怪的是，它的速度只有两倍",
    "Triple core Chipset": "三核芯片组",
    "Can you even lift?": "你能举起东西吗？",
    "Get Out of Jail Free Card": "免费出狱卡",
    "Higher lifting": "更高的提升",
    "Hmm seems there's a card missing in this game": "看来这个游戏少了一张牌",
    "No gift will escape": "没有礼物能逃脱",
    "Radar Techonology": "雷达技术",
    "Even Santa can’t comprehend this": "连圣诞老人都无法理解",
    "No need to unwrap the gift": "不需要拆开礼物",
    "X-ray Scanner": "X射线扫描器",
    "Brrr chilly": "呜呜呜，好冷",
    "Cooling system": "冷却系统",
    "Doesn't get stuck in the machine": "不会卡在机器里",
    "Double rainbow what does it mean?": "双重彩虹是什么意思?",
    "For a silent approach": "为了一个安静的方法",
    "Nano gift paper": "纳米礼品纸",
    "Owl Wings": "猫头鹰翅膀",
    "Rainbow gifts": "彩虹礼物",
    "Never out of sync again": "再也不会不同步了",
    "Optic Fiber": "光纤",
    "Can handle heavier gifts": "能处理较重的礼物",
    "Counter Weight": "配重块",
    "No more looking for outlets": "不用再寻找出路了",
    "Shopping Cart": "购物车",
    "Abandoned cookie factory": "废弃的饼干工厂",
    "Night Vision": "夜视",
    "Bring up the speed of lightning": "提升闪电般的速度",
    "Light Lightining": "光之闪电",
    "Chains": "锁链",
    "Nobody leaves their machine": "没有人离开他们的机器",
    "Every atom is duplicated": "每个原子都是复制的",
    "Quantum Printing": "量子印刷",
    "A traveling merchant with a silver tongue offers you a deal. He claims his goods will make you more persuasive, for a price.": "一个能说会道的旅行商人给你提供了一笔交易。他声称他的商品会让你更有说服力，但要付出代价。",
    "At the edge of the bustling square, a merchant draped in colorful silks waves you over. His voice is silky and persuasive as he offers a deal that seems too good to be true.": "在熙熙攘攘的广场边上，一位身披彩色丝绸的商人向你招手。他的声音柔滑而有说服力，因为他提出了一个似乎好得令人难以置信的交易。",
    "Buy the Goods": "购买商品",
    "Charismatic Merchant": "魅力商人",
    "Coins Earned Bonus": "获得金币加成",
    "Knowledge Debuff": "减益魔法知识",
    "Refuse": "拒绝",
    "Take the deal": "接受协议",
    "The deal pays off handsomely! Your gold income increases for the next 5 minutes.": "这笔交易回报丰厚！你的金币收入会在接下来的5分钟内增加。",
    "The merchant’s goods grant you an air of confidence. (+1 Charisma)": "商人的货物给你一种自信的感觉。(+ 1魅力)",
    "Walk Away": "走开",
    "You destroy the artifact, and a wave of energy heals you. (+20% HP)": "你摧毁了神器，一股能量的波动治愈了你。（生命值+20%）",
    "You feel yourself dummy. Your knowledge gain is decreased": "你觉得自己很笨。你获得的知识减少了",
    "You overexert yourself and feel drained. (-Knowledge gain for 5 minutes)": "你过度劳累，感觉筋疲力尽。（-5分钟知识增益）",
    "Your coins income is boosted": "你的金币收入增加了",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "Email: contact[[at]]santaception.com": "Email: contact[[at]]santaception.com",
    "t": "t",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "Scientific": "科学计数法",
    "Standard": "标准",
    "Blind": "盲文",
    "Letters": "字母",
    "Mixed Engineering": "混合工程",
    "Mixed Scientific": "混合科学",
    "Chemistry": "化学",
    "Engineering": "工程符号",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "信息",
    "settings": "settings",
    'Twitter': 'Twitter',
    "Discord": "Discord",
    "Facebook": "Facebook",
    "Instagram": "Instagram",
    "gityxcom": "gityxcom",
    "Footer": "Footer",
    "Wiki": "Wiki",
    "gityx": "gityx",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    'i': 'i',
    'I': 'I',
    'II': 'II',
    'III': 'III',
    'IV': 'IV',
    'V': 'V',
    'VI': 'VI',
    'VII': 'VII',
    'VIII': 'VIII',
    'X': 'X',
    'XI': 'XI',
    'XII': 'XII',
    'XIII': 'XIII',
    'XIV': 'XIV',
    'XV': 'XV',
    'XVI': 'XVI',
    'A': 'A',
    'B': 'B',
    'C': 'C',
    'D': 'D',
    'E': 'E',
    'F': 'F',
    'G': 'G',
    'H': 'H',
    'I': 'I',
    'J': 'J',
    'K': 'K',
    'L': 'L',
    'M': 'M',
    'N': 'N',
    'O': 'O',
    'P': 'P',
    'Q': 'Q',
    'R': 'R',
    'S': 'S',
    'T': 'T',
    'U': 'U',
    'V': 'V',
    'W': 'W',
    'X': 'X',
    'Y': 'Y',
    'Z': 'Z',
    '<': '<',
    '<<': '<<',
    '>': '>',
    '>>': '>>',
    'Jan': '1月',
    'Feb': '2月',
    'Mar': '3月',
    'Apr': '4月',
    'May': '5月',
    'Jun': '6月',
    'Jul': '7月',
    'Aug': '8月',
    'Sep': '9月',
    'Oct': '10月',
    'Nov': '11月',
    'Dec': '12月',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀，此处可以截取语句开头部分的内容进行汉化
//例如：Coin: 13、Coin: 14、Coin: 15... 这种有相同开头的语句
//可以在这里汉化开头："Coin: ":"金币: "
var cnPrefix = {
    "\n": "\n",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": " ",
    " ": " ",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "Notation: ": "符号: ",
    "Toggle Music: ": "切换声音: ",
    "total production:": "总产量：",
    "Steal ": "偷取 ",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀，此处可以截取语句结尾部分的内容进行汉化
//例如：13 Coin、14 Coin、15 Coin... 这种有相同结尾的语句
//可以在这里汉化结尾：" Coin":" 金币"
var cnPostfix = {
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "  ",
    " ": " ",
    "\n": "\n",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "/sec)": "/秒)",
    ' I': ' I',
    ' II': ' II',
    ' III': ' III',
    ' IV': ' IV',
    ' V': ' V',
    ' VI': ' VI',
    ' VII': ' VII',
    ' VIII': ' VIII',
    ' X': ' X',
    ' XI': ' XI',
    ' XII': ' XII',
    ' XIII': ' XIII',
    ' XIV': ' XIV',
    ' XV': ' XV',
    ' XVI': ' XVI',
    "% bonus gifts)": "% 奖励的礼物)",
    " total)": " 总计)",
    "% gift production": "% 礼物生产",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)h$/,
    /^([\d\.]+)m$/,
    /^([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^v ([\d\.]+)$/,
    /^\$([\d\.]+)$/,
    /^\(([\d\.]+)\)$/,
    /^([\d\.]+)\%$/,
    /^([\d\.]+)\/([\d\.]+)$/,
    /^([\d\.]+)\/([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.,]+)$/,
    /^\(([\d\.]+)\/([\d\.]+)\)$/,
    /^成本(.+)$/,
    /^\-(.+)$/,
    /^\(([\d\.]+)\%\)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)K$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) Billion$/,
    /^([\d\.]+) Million$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+) T$/,
    /^([\d\.]+) Qi$/,
    /^([\d\.]+) Qa$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^\$([\d\.,]+)$/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+) \/ ([\d\.]+)e([\d\.,]+)$/,
    /^\$([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e\+([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])|[\u21A9\u21AA\u25B6\u25C0\u2B06\u2B07\u2B05\u2B95\u2B99\u2B9A]+$/,
    // /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])+$/,
    // /^[\uD800-\uFFFF]+$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//字母加数字：([\d\.]+[A-Za-z])
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
//&nbsp;空格：\xA0
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
    [/Click (.+) gifts$/, '点击 $1 礼物'],
    [/Make (.+) gifts$/, '制作 $1 礼物'],
    [/Make (.+) gifts from clicking$/, '通过点击制作 $1 礼物'],
    [/Make (.+) gift$/, '制作 $1 礼物'],
    [/Achieve (.+) Achievement Achievements$/, '达成 $1 成就的成就'],
    [/Achieve (.+) Achievements$/, '达成 $1 成就'],
    [/Develop (.+) upgrades$/, '发展 $1 升级'],
    [/produces (.+) each second$/, '每秒产生 $1 个'],
    [/Deliver all gifts to earth by using your toy machine less than (.+) times$/, '使用你的玩具机器少于 $1 次，把所有的礼物送到地球'],
    [/Buy (.+) upgrades$/, '购买 $1 升级'],
    [/Catch (.+) golden gifts$/, '捕捉 $1 金色礼物'],
    [/Have at least (.+) items of each$/, '每种物品至少有 $1 件'],
    [/^Unlock (.+) of your Santasperience$/, '解锁 $1 你的圣诞经验值'],
    [/^(.+) january \- (.+):(.+)$/, '1 月 $1 日 \- $2:$3'],
    [/^(.+) february \- (.+):(.+)$/, '2 月 $1 日 \- $2:$3'],
    [/^(.+) march \- (.+):(.+)$/, '3 月 $1 日 \- $2:$3'],
    [/^(.+) april \- (.+):(.+)$/, '4 月 $1 日 \- $2:$3'],
    [/^(.+) may \- (.+):(.+)$/, '5 月 $1 日 \- $2:$3'],
    [/^(.+) june \- (.+):(.+)$/, '6 月 $1 日 \- $2:$3'],
    [/^(.+) july \- (.+):(.+)$/, '7 月 $1 日 \- $2:$3'],
    [/^(.+) august \- (.+):(.+)$/, '8 月 $1 日 \- $2:$3'],
    [/^(.+) september \- (.+):(.+)$/, '9 月 $1 日 \- $2:$3'],
    [/^(.+) october \- (.+):(.+)$/, '10 月 $1 日 \- $2:$3'],
    [/^(.+) november \- (.+):(.+)$/, '11 月 $1 日 \- $2:$3'],
    [/^(.+) december \- (.+):(.+)$/, '12 月 $1 日 \- $2:$3'],
    [/^Jan ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 1 月 $1, $3:$4'],
    [/^Feb ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 2 月 $1, $3:$4'],
    [/^Mar ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 3 月 $1, $3:$4'],
    [/^Apr ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 4 月 $1, $3:$4'],
    [/^May ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 5 月 $1, $3:$4'],
    [/^Jun ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 6 月 $1, $3:$4'],
    [/^Jul ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 7 月 $1, $3:$4'],
    [/^Aug ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 8 月 $1, $3:$4'],
    [/^Sep ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 9 月 $1, $3:$4'],
    [/^Oct ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 10 月 $1, $3:$4'],
    [/^Nov ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 11 月 $1, $3:$4'],
    [/^Dec ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 12 月 $1, $3:$4'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.,]+) Gift$/, '$1 礼物'],
    [/^([\d\.,]+) Gifts$/, '$1 礼物'],
    [/^(.+) per second$/, '$1 每秒'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^([\d\.,]+) Elves$/, '$1 精灵'],
    [/^([\d\.,]+) Robot$/, '$1 机器人'],
    [/^([\d\.,]+) Robots$/, '$1 机器人'],
    [/^([\d\.,]+) Vortex Machine$/, '$1 涡漩机'],
    [/^([\d\.,]+) Vortex Machines$/, '$1 涡漩机'],
    [/^([\d\.,]+) Conveyor$/, '$1 传送带'],
    [/^([\d\.,]+) Conveyors$/, '$1 传送带'],
    [/^([\d\.,]+) Duplicator$/, '$1 复制器'],
    [/^([\d\.,]+) Duplicators$/, '$1 复制器'],
    [/^([\d\.,]+) Planet$/, '$1 星球'],
    [/^([\d\.,]+) Planets$/, '$1 星球'],
    [/^([\d\.,]+) Factory$/, '$1 工厂'],
    [/^([\d\.,]+) Factories$/, '$1 工厂'],
    [/^([\d\.,]+) Elf$/, '$1 精灵'],
    [/^([\d\.,]+) Elfs$/, '$1 精灵'],
    [/^([\d\.,]+) Forklift$/, '$1 叉车'],
    [/^([\d\.,]+) Forklifts$/, '$1 叉车'],
    [/^([\d\.,]+) Giftwrapper$/, '$1 礼物包装器'],
    [/^([\d\.,]+) Giftwrappers$/, '$1 礼物包装器'],
    [/^([\d\.,]+) Toy Machine$/, '$1 玩具机器'],
    [/^([\d\.,]+) Toy Machines$/, '$1 玩具机器'],
    [/^([\d\.,]+) Toy Thief$/, '$1 玩具小偷'],
    [/^([\d\.,]+) Toy Thieves$/, '$1 玩具小偷'],
    [/^Have ([\d\.,]+) Toy Machine$/, '拥有 $1 玩具机器'],
    [/^Have ([\d\.,]+) Toy Machines$/, '拥有 $1 玩具机器'],
    [/^Have ([\d\.,]+) Toy Thief$/, '拥有 $1 玩具小偷'],
    [/^Have ([\d\.,]+) Toy Thieves$/, '拥有 $1 玩具小偷'],
    [/^Have ([\d\.,]+) Forklift$/, '拥有 $1 叉车'],
    [/^Have ([\d\.,]+) Planet$/, '拥有 $1 星球'],
    [/^Have ([\d\.,]+) Planets$/, '拥有 $1 星球'],
    [/^Have ([\d\.,]+) Factory$/, '拥有 $1 工厂'],
    [/^Have ([\d\.,]+) Factories$/, '拥有 $1 工厂'],
    [/^Have ([\d\.,]+) Conveyor$/, '拥有 $1 传送带'],
    [/^Have ([\d\.,]+) Conveyors$/, '拥有 $1 传送带'],
    [/^Have ([\d\.,]+) Robot$/, '拥有 $1 机器人'],
    [/^Have ([\d\.,]+) Robots$/, '拥有 $1 机器人'],
    [/^Have ([\d\.,]+) Forklifts$/, '拥有 $1 叉车'],
    [/^Have ([\d\.,]+) Duplicator$/, '拥有 $1 复制器'],
    [/^Have ([\d\.,]+) Duplicators$/, '拥有 $1 复制器'],
    [/^Have ([\d\.,]+) Vortex Machine$/, '拥有 $1 涡漩机'],
    [/^Have ([\d\.,]+) Vortex Machines$/, '拥有 $1 涡漩机'],
    [/^Have ([\d\.,]+) items$/, '拥有 $1 物品'],
    [/^Have ([\d\.,]+) Elves$/, '拥有 $1 精灵'],
    [/^Have ([\d\.,]+) Elf$/, '拥有 $1 精灵'],
    [/^Have ([\d\.,]+) Elfs$/, '拥有 $1 精灵'],
    [/^Have ([\d\.,]+) Giftwrapper$/, '拥有 $1 礼物包装器'],
    [/^Have ([\d\.,]+) Giftwrappers$/, '拥有 $1 礼物包装器'],
    [/^Day ([\d\.,]+)$/, '天数 $1'],
    [/^level ([\d\.,]+) \/ ([\d\.,]+)$/, '等级 $1 \/ $2'],
    [/^level: ([\d\.,]+) \/ ([\d\.,]+)$/, '等级 $1 \/ $2'],
    [/^(.+) Gifts$/, '$1 礼物'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);